#!/bin/bash
#
# Controls to build and manipulate jar archives
#
# jar options
#
# c - create new jar
# u - update jar
# x - extract jar
#
# v - verbose
# f - create file
# m - specify Manifest.txt
# e - specify program entry point
#

COMPILED='*.jar'
MANIFEST="Manifest.txt"

program=$(basename "$0")
action="$1"

# throw away action from command line arguments
shift


clean() {
        for file in $COMPILED
        do
                rm -f "$file"
        done
}


create_jar() {

        use_manifest=false

        if [[ "$1" = "$MANIFEST" ]]; then
                use_manifest=true
                shift
        else
                entry_point="${1%.*}"
        fi

        jar_name="${1%.*}.jar"

        if [[ "$use_manifest" = true ]]; then
                jar cvfm "$jar_name" "$MANIFEST" "$@"
        else
                jar cvfe "$jar_name" "$entry_point" "$@"
        fi
}


case "$action" in
        create)
                create_jar "$@"
                ;;
        clean)
                clean
                ;;
        *)
                echo "Error!"
                exit 1
                ;;
esac

