#!/bin/bash

JUNIT="/usr/share/java/junit-4.12.jar"
HAMCREST="/usr/share/java/hamcrest/core-1.3.jar"
RUNCLASS="org.junit.runner.JUnitCore"

SOURCE="src"
CLASSES="classes"

program=$(basename "$0")
action="$1"

# throw away action from command line arguments
shift

compile() {
        javac -d classes -classpath $SOURCE:$JUNIT $SOURCE/"$1"/*.java
}


testing() {
        java -classpath $CLASSES:$JUNIT:$HAMCREST "$RUNCLASS" "$1.$2"
}

testall() {
        for file in $CLASSES/$1/*
        do
                if [[ $file =~ Test.class ]]; then
                        file=${file##*/}
                        testing "$1" ${file%.*}
                fi
        done
}


run() {
        java -classpath $CLASSES "$1.$2"
}


case "$action" in
        compile)
                compile "$1"
                ;;
        testing)
                testing "$1" "$2"
                ;;
        testall)
                testall "$1"
                ;;
        run)
                run "$1" "$2"
                ;;
        *)
                echo "Error!"
                ;;
esac
