#!/bin/bash
#
# Script assumes the classes to be tested and the junit tests
# are all in the same directory
#

JUNIT="/usr/share/java/junit-4.12.jar"
HAMCREST="/usr/share/java/hamcrest/core-1.3.jar"
RUNCLASS="org.junit.runner.JUnitCore"
COMPILED='*.class'

program=$(basename "$0")
action="$1"

# throw away action from command line arguments
shift


usage() {
        printf "\nUsage: $program command [target]\n\n"
        printf '%-10s%-25s%-25s \n' "help" "" "display this message"
        printf '%-10s%-25s%-25s \n' "clean" "" "delete all compiled files"
        printf '%-10s%-25s%-25s \n' "compile" "TestClassName.java" "compile the tests"
        printf '%-10s%-25s%-25s \n' "run" "TestClassName" "run the tests"
        printf '%-10s%-25s%-25s \n' "full" "TestClassName.java" "compile and run the tests"
        printf "\ncompile, run and full can all take multiple test files as arguments\n\n"
}


clean() {
        for file in $COMPILED
        do
                rm -f "$file"
        done
}


compile() {
        if [[ -f "$1" ]]; then
                javac -classpath "$(pwd)":"$JUNIT" "$1"
        else
                echo "File '$1' not found"
        fi
}


compile_all() {
        for test_source in "$@"
        do
                compile "${test_source%.*}.java"
        done
}


run() {
        if [[ -f "${1}.class" ]]; then
                java -classpath "$(pwd)":"$JUNIT":"$HAMCREST" "$RUNCLASS" "$1"
        else
                echo "junit tests '$1' not found"
        fi
}


run_all() {
        for junit_test in "$@"
        do
                run "${junit_test%.*}"
        done
}


error_exit() {
        echo "Unrecognised command: '$action'"
        usage
        exit 1
}


case "$action" in
        compile)
                clean && compile_all "$@"
                ;;
        run)
                run_all "$@"
                ;;
        full)
                clean && compile_all "$@" && run_all "$@"
                ;;
        clean)
                clean
                ;;
        help)
                usage
                ;;
        *)
                error_exit
                ;;
esac
