#!/bin/bash
#
# Script assumes the classes to be tested and the junit tests
# are all in the same directory
#

program=$(basename "$0")
action="$1"
testclass="$2"

junit="/usr/share/java/junit-4.12.jar"
hamcrest="/usr/share/java/hamcrest/core-1.3.jar"
runclass="org.junit.runner.JUnitCore"

compiled='*.class *.jar'


usage() {
        printf "\nUsage: $program command [target]\n\n"
        printf '%-10s%-25s%-25s \n' "help" "" "display this message"
        printf '%-10s%-25s%-25s \n' "clean" "" "delete all compiled files"
        printf '%-10s%-25s%-25s \n' "compile" "TestClassName.java" "compile the tests"
        printf '%-10s%-25s%-25s \n' "run" "TestClassName" "run the tests"
        printf '%-10s%-25s%-25s \n' "full" "TestClassName.java" "compile and run the tests"
}


clean() {
        for file in $compiled
        do
                rm -f "$file"
        done
}


compile() {
        if [[ -f "$1" ]]; then
                javac -classpath "$(pwd)":"$junit" "$1"
        else
                echo "File '$1' not found"
        fi
}


run() {
        if [[ -f "${1%.*}.class" ]]; then
                java -classpath "$(pwd)":"$junit":"$hamcrest" "$runclass" "$1"
        else
                echo "junit tests '$1' not found"
        fi
}


error_exit() {
        echo "Unrecognised command: '$1'"
        usage
        exit 1
}


case "$action" in
        compile)
                clean && compile "$testclass"
                ;;
        run)
                run "${testclass%.*}"
                ;;
        full)
                clean && compile "$testclass" && run "${testclass%.*}"
                ;;
        clean)
                clean
                ;;
        help)
                usage
                ;;
        *)
                error_exit "$action"
                ;;
esac
