#!/bin/bash
#
# Script assumes the classes to be tested and the junit tests
# are all in the same directory
#

action="$1"
testclass="$2"

junit="/usr/share/java/junit-4.12.jar"
hamcrest="/usr/share/java/hamcrest/core-1.3.jar"
runclass="org.junit.runner.JUnitCore"

case "$action" in
        compile)
                javac -classpath "$(pwd)":"$junit" "$testclass"
                ;;
        run)
                java -classpath "$(pwd)":"$junit":"$hamcrest" "$runclass" "${testclass%.*}"
                ;;
        *)
                echo "Unrecognised action: $1"
                ;;
esac
