#!/bin/bash

REPO_DIR="/home/james/hetznerNextcloud/pacman_repo"
REPO_NAME="custom.db.tar.gz"
PACKAGE_NAME="$1"


mv $PACKAGE_NAME $REPO_DIR && echo "Package moved to $REPO_DIR"

echo

repo-add $REPO_DIR/$REPO_NAME $REPO_DIR/$PACKAGE_NAME

