#!/bin/bash


set_passphrase() {
        
        case "$1" in
                "newArch-home")
                        export BORG_PASSPHRASE=$HOME_PASSPHRASE
                        ;;
                "newArch-system")
                        export BORG_PASSPHRASE=$SYSTEM_PASSPHRASE
                        ;;
                "nextcloud")
                        export BORG_PASSPHRASE=$NEXTCLOUD_PASSPHRASE
                        ;;
                "Sync")
                        export BORG_PASSPHRASE=$SYNC_PASSPHRASE
                        ;;
                *)
                        { echo "'$2' is not a repo"; exit 1; }
                        ;;
        esac
}
