#!/bin/bash

[[ -f ${HOME}/.credentials ]] \
        && . ${HOME}/.credentials \
        || { echo "Credentials not found"; exit 1; }


. borg_utils_shared


operation="$1"
repo="$2"
archive="$3"
path="$4"
new_name="$4"


case $operation in
        "unmount")
                unmount
                exit 0
                ;;
esac


[[ $# -lt 3 ]] && { echo "Not enough arguments"; exit 1; }



set_passphrase $repo


case $operation in
        "list")
                list $repo $archive
                ;;
        "check")
                check $repo $archive
                ;;
        "delete")
                delete $repo $archive
                ;;
        "mount")
                mount $repo $archive
                ;;
        "extract")
                extract $repo $archive $path
                ;;
        "rename")
                rename $repo $archive $new_name
                ;;
        *)
                { echo "Illegal operation"; exit 1; }
                ;;
esac


unset BORG_PASSPHRASE


exit 0
