#!/bin/bash


set_passphrase() {
        
        case "$1" in
                "newArch-home")
                        export BORG_PASSPHRASE=$HOME_PASSPHRASE
                        ;;
                "newArch-system")
                        export BORG_PASSPHRASE=$SYSTEM_PASSPHRASE
                        ;;
                "nextcloud")
                        export BORG_PASSPHRASE=$NEXTCLOUD_PASSPHRASE
                        ;;
                "Sync")
                        export BORG_PASSPHRASE=$SYNC_PASSPHRASE
                        ;;
                *)
                        { echo "'$2' is not a repo"; exit 1; }
                        ;;
        esac
}


list() {
        borg list --remote-path=borg1 \
                $RSYNC_DOT_NET_USER@$RSYNC_DOT_NET_DOMAIN:"$1"
}


check() {
        borg check --remote-path=borg1 \
                $RSYNC_DOT_NET_USER@$RSYNC_DOT_NET_DOMAIN:"$1"
}


delete() {
        borg delete --remote-path=borg1 \
                $RSYNC_DOT_NET_USER@$RSYNC_DOT_NET_DOMAIN:"$1"
}


create() {
        borg init --remote-path=borg1 --encryption=keyfile \
                $RSYNC_DOT_NET_USER@$RSYNC_DOT_NET_DOMAIN:"$1"
}
