#!/bin/bash

[[ -f /home/james/.credentials ]] \
        && . /home/james/.credentials \
        || { echo "Credentials not found"; exit 1; }

. borg_utils_shared


case "$1" in
        "unmount")
                unmount
                exit 0
                ;;
esac


[[ $# -lt 3 ]] && { echo "Not enough arguments"; exit 1; }


set_passphrase "$2"


operation="$1"
shift


case $operation in
        "list")
                list "$@"
                ;;
        "check")
                check "$@"
                ;;
        "delete")
                delete "$@"
                ;;
        "mount")
                mount "$@"
                ;;
        "extract")
                extract "$@"
                ;;
        "rename")
                rename "$@"
                ;;
        *)
                { echo "Illegal operation"; exit 1; }
                ;;
esac

unset BORG_PASSPHRASE
exit 0
