#!/bin/bash

[[ -f ${HOME}/.credentials ]] \
        && . ${HOME}/.credentials \
        || { echo "Credentials not found"; exit 1; }

. borg_utils_shared


[[ ! $# -eq 2 ]] && { echo "Not enough arguments"; exit 1; }


operation="$1"
repo="$2"


case $operation in
        "create")
                create $repo
                exit 0
                ;;
esac


set_passphrase $repo


case $operation in
        "list")
                list $repo
                ;;
        "check")
                check $repo
                ;;
        "delete")
                delete $repo
                ;;
        *)
                { echo "Illegal operation"; exit 1; }
                ;;
esac

unset BORG_PASSPHRASE
exit 0
