#!/bin/bash

[[ -f /home/james/.credentials ]] \
        && . /home/james/.credentials \
        || { echo "Credentials not found"; exit 1; }

. borg_utils_shared


[[ ! $# -eq 2 ]] && { echo "Not enough arguments"; exit 1; }


operation="$1"
repo="$2"


list() {
        borg list --remote-path=borg1 \
                $RSYNC_DOT_NET_USER@$RSYNC_DOT_NET_DOMAIN:"$1"
}

check() {
        borg check --remote-path=borg1 \
                $RSYNC_DOT_NET_USER@$RSYNC_DOT_NET_DOMAIN:"$1"
}

delete() {
        borg delete --remote-path=borg1 \
                $RSYNC_DOT_NET_USER@$RSYNC_DOT_NET_DOMAIN:"$1"
}

create() {
        borg init --remote-path=borg1 --encryption=keyfile \
                $RSYNC_DOT_NET_USER@$RSYNC_DOT_NET_DOMAIN:"$1"
}


case $operation in
        "create")
                create $repo
                exit 0
                ;;
esac


set_passphrase "$2"


case $operation in
        "list")
                list $repo
                ;;
        "check")
                check $repo
                ;;
        "delete")
                delete $repo
                ;;
        *)
                { echo "Illegal operation"; exit 1; }
                ;;
esac

unset BORG_PASSPHRASE
exit 0
