#!/bin/bash


NOTE_DIR="/home/james/latex_projects/notes"
HTML_DIR="/home/james/latex_projects/notes/docs"
MD_FILE="readme.md"


to_html() {
        pandoc -s "$1" -o "${1%.*}.html"
}


to_markdown() {
        pandoc -s "${1%.*}.html" -o "$MD_FILE"
}


do_conversions() {
        to_html "$1" && to_markdown "${1%.*}.html"
}


add_custom_css() {
        sed -i 's/<\/style>/<\/style>\n<link rel="stylesheet" href="index.css">/' "$1"
}


augment_html() {
        add_custom_css "$1"
}


update_single_page() {
        target="${PWD##*/}"

        for file in *
        do
                if [[ -f "$target.tex" ]]; then
                        do_conversions "$target.tex" && \
                        augment_html "$target.html" && \
                        mv "$target.html" "$HTML_DIR"
                fi
        done
}


update_all_pages() {
        cd "$NOTE_DIR"
        for note in *
        do
                if [[ -d "$note" ]]; then
                        cd "$note" && update_single_page && cd ..
                fi
        done
}


case "$1" in
        "all")
                update_all_pages
                ;;
        *)
                update_single_page
                ;;
esac
