#!/bin/bash


NOTE_DIR="/home/james/latex_projects/notes"
HTML_DIR="/home/james/latex_projects/notes/docs"
MD_FILE="readme.md"



is_new_note() {
        return $(grep -q "$1.html" "$HTML_DIR/index.html")
}


place_note_in_index() {
        note_name="$(echo "$1" | sed 's/_/ /g')"
        note_url="$1.html"

        old_start="<ul id=\"notes-list\">"
        new_entry="<li><a class=\"note-link\" href=\"$note_url\">$note_name<\/a><\/li>"

        sed -i "s/$old_start/$old_start\n $new_entry/" "$HTML_DIR/index.html"
}


to_html() {
        pandoc -s "$1" -o "${1%.*}.html"
}


to_markdown() {
        pandoc -s "${1%.*}.html" -o "$MD_FILE"
}


do_conversions() {
        to_html "$1" && to_markdown "${1%.*}.html"
}


add_custom_css() {
        sed -i 's/<\/style>/<\/style>\n<link rel="stylesheet" href="index.css">/' "$1"
}


augment_html() {
        add_custom_css "$1"
}


update_single_page() {
        target="${PWD##*/}"

        for file in *
        do
                if [[ -f "$target.tex" ]]; then
                        do_conversions "$target.tex" && \
                        augment_html "$target.html" && \
                        mv "$target.html" "$HTML_DIR"

                fi
        done

        is_new_note "$target"

        if [[ $? -gt 0 && -f "$HTML_DIR/$target.html" ]]; then
                place_note_in_index "$target"
        fi
}


update_all_pages() {
        cd "$NOTE_DIR"
        for note in *
        do
                if [[ -d "$note" ]]; then
                        cd "$note" && update_single_page && cd "$NOTE_DIR"
                fi
        done
}


case "$1" in
        "all")
                update_all_pages
                ;;
        *)
                update_single_page
                ;;
esac
