#!/bin/bash

[[ -f ${HOME}/.credentials ]] \
        && . ${HOME}/.credentials \
        || { echo "Credentials not found"; exit 1; }


[[ -f /usr/lib/borgctl_utils.sh ]] && . /usr/lib/borgctl_utils.sh


program=$(basename "$0")


operation="$1"
repo="$2"
archive="$3"
path="$4"
new_name="$4"


[[ -z $operation ]] && { usage; exit 1; }


case $operation in
        "help")
                usage
                exit 0
                ;;
        "unmount")
                unmount
                exit 0
                ;;
        "init")
                init $repo
                exit 0
                ;;
esac


set_passphrase $repo


case $operation in
        "list")
                list $repo $archive
                ;;
        "check")
                check $repo $archive
                ;;
        "delete")
                delete $repo $archive
                ;;
        "mount")
                mount $repo $archive
                ;;
        "extract")
                extract $repo $archive $path
                ;;
        "rename")
                rename $repo $archive $new_name
                ;;
        *)
                { usage; exit 1; }
                ;;
esac


unset BORG_PASSPHRASE


exit 0
